"""Phase 2 cluster 3: verify qrK, psdframeit, psdinvjmul, sqrtinv,
givensrot, urotorder, invcholfac (the PSD-cone scaling-point kernels)
against the real Octave/MEX build.

Scope: real-symmetric PSD blocks only (K.rsdpN == K.sdpN, i.e. no
complex Hermitian blocks) -- the complex-Hermitian code paths in each of
these files are not covered by the Python port yet.

Oracle data (tests/fixtures/cluster3/*.mat) is generated by
python_port/tools/generate_cluster3_oracle.m and committed, so this test
does not require Octave to be installed to run.
"""

from pathlib import Path

import numpy as np
import pytest
import scipy.io

sedumi_port = pytest.importorskip("sedumi_port")
from sedumi_port import _native  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "cluster3"
pytestmark = pytest.mark.skipif(
    not FIXTURE_DIR.exists(), reason="cluster3 fixtures not generated"
)


def _K():
    data = scipy.io.loadmat(FIXTURE_DIR / "K.mat")
    Kstruct = data["K"][0, 0]
    return {"s": Kstruct["s"].ravel().tolist()}


def test_qrK_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "qrK.mat")
    frms, r = _native.qrK(data["x"].ravel(), _K())
    np.testing.assert_allclose(frms, data["frms"].ravel(), rtol=1e-10)
    np.testing.assert_allclose(r, data["r"].ravel(), rtol=1e-10)


def test_psdframeit_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "psdframeit.mat")
    xf = _native.psdframeit(data["lab"].ravel(), data["frms"].ravel(), _K())
    np.testing.assert_allclose(xf, data["xf"].ravel(), rtol=1e-10)


def test_sqrtinv_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "sqrtinv.mat")
    y = _native.sqrtinv(data["frms"].ravel(), data["vlab"].ravel(), _K())
    np.testing.assert_allclose(y, data["ysq"].ravel(), rtol=1e-10)


def test_psdinvjmul_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "psdinvjmul.mat")
    z = _native.psdinvjmul(
        data["evx"].ravel(), data["frms"].ravel(), data["yin"].ravel(), _K()
    )
    np.testing.assert_allclose(z, data["zout"].ravel(), rtol=1e-10)


def test_invcholfac_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "invcholfac.mat")
    K = _K()
    y_noperm = _native.invcholfac(data["u"].ravel(), K)
    np.testing.assert_allclose(y_noperm, data["y_noperm"].ravel(), rtol=1e-10)

    y_perm = _native.invcholfac(data["u"].ravel(), K, data["permv"].ravel())
    np.testing.assert_allclose(y_perm, data["y_perm"].ravel(), rtol=1e-10)


def test_urotorder_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "urotorder.mat")
    K = _K()
    u_out, perm, gjc, g = _native.urotorder(
        data["u2"].ravel(), K, float(data["maxu"].item())
    )
    np.testing.assert_allclose(u_out, data["u_out"].ravel(), rtol=1e-8, atol=1e-10)
    np.testing.assert_array_equal(perm, data["perm"].ravel())
    np.testing.assert_array_equal(gjc, data["gjc"].ravel())
    np.testing.assert_allclose(g, data["g"].ravel(), rtol=1e-8, atol=1e-10)


def test_givensrot_matches_octave_mex():
    data = scipy.io.loadmat(FIXTURE_DIR / "givensrot.mat")
    Kstruct = data["K"][0, 0]
    K = {"s": Kstruct["s"].ravel().tolist()}
    y = _native.givensrot(data["gjc"].ravel(), data["g"].ravel(), data["xg"].ravel(), K)
    np.testing.assert_allclose(y, data["yg"].ravel(), rtol=1e-10)


def test_psdframeit_reconstructs_symmetric_matrix_from_its_own_eigenvalues():
    """Independent of the oracle: psdframeit(lab, frms, K) with frms from
    qrK(x, K) and lab = the diagonal of R'*R (NOT a real eigendecomposition,
    just a self-consistent check) must at least produce a symmetric result
    per block -- psdframeit's own defining property (X = Q'*diag(lab)*Q is
    always symmetric for any real lab, any orthogonal-ish Q)."""
    data = scipy.io.loadmat(FIXTURE_DIR / "qrK.mat")
    K = _K()
    frms = data["frms"].ravel()

    block_sizes = [int(v) for v in K["s"]]
    lab = np.concatenate([np.arange(1, nk + 1, dtype=np.float64) for nk in block_sizes])
    xf = _native.psdframeit(lab, frms, K)

    off = 0
    for nk in block_sizes:
        block = xf[off : off + nk * nk].reshape(nk, nk, order="F")
        np.testing.assert_allclose(block, block.T, atol=1e-10)
        off += nk * nk
